Iter15
kamencov/go-musthave-shortener-tpl pull request #17
Opened 2024-09-01 09:06 UTC by kamencov

2024-09-04 03:00 UTC, vokinneberg requested changes
Поздравляю с первым ревью четвёртого спринта! 🎉 В этом спринте мы коснулись, наверное, самых сложных тем: многопоточности и криптографии. Хочу сделать несколько предложений по улучшению и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и проходит тесты! 🚀
2. Ты лаконично встроил новый функционал в структуру приложения. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Не совсем понятно, для чего использовать такую реализацию. Насколько мне удалось разобраться, сначала мы отправляем список URL на удаление в `FanIn`, разбиваем его на отдельные URL и отправляем их в общий канал, который читает метод `DeletedURLs(...)` — который, в свою очередь, собирает эти URL обратно в общий список и отправляет на удаление, и, ожидая завершения удаления, возвращает управление. Проблема в том, что если мы уберём это и просто отправим список на удаление в `updateDatabase(...)`, ничего не изменится.
    
    Дело в том, что эта реализация к тому же не совсем соответствует постановке задачи: *В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted. Фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно.*
    
    Мне кажется, что простая реализация могла бы выглядеть как-то так:
    
    - При старте приложения мы запускаем горутину (воркер) или несколько воркеров (я рекомендую начать с одного) в методе `main`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
    - Хендлеры, получив запрос на удаление, отправляют задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращают ответ пользователю.
2. Проверку отсутствия `userID` было бы эффективнее вынести в middleware.
3. Так как мы модифицируем базу в существующем приложении, база может уже существовать, соответственно стоит расширять её либо отдельной командой, либо использовать миграции.
4. Было бы здорово реализовать обратную совместимость для других типов хранилищ.
5. Было бы здорово реализовать тесты новых сценариев.

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/filestorage/getFile.go
> +func (s *SaveFile) GetAllURL(userID, baseURL string) ([]*models.UserURLs, error) {
Было бы здорово реализовать обратную совместимость для других типов хранилищ.

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/mapstorage/mapStorage.go
> +func (s *MapStorage) GetAllURL(userID, baseURL string) ([]*models.UserURLs, error) {
Было бы здорово реализовать обратную совместимость для других типов хранилищ.

2024-09-04 03:00 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	if !ok || userID == "" {
Мне кажется такую проверку стоит вынести в middleware.

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/db/checkOriginalURL.go
> +	return nil
Мне кажется не совсем верно называть переменную `err`, так как это в реальности не ошибка. Можно так же немного сократить запись.
```suggestion
	if row := p.storage.QueryRowContext(context.Background(),
		"SELECT user_id FROM urls WHERE user_id = $1",
		user); row.Err() != nil {
		return row.Err()
	}
	return nil
```

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/db/saveDB.go
> +	}
Все-таки не стоит использовать `interface{}` там, где известен тип переменной. Если необходимо чтобы строка была nullable, можно использовать указатель.
```suggestion
	var user *string
	if userID != "" {
		user = userID
	}
```

2024-09-04 03:00 UTC, vokinneberg commented on internal/templates/fanIn.go
> +func FanIn(doneCh chan struct{}, sliceURLs []string) chan string {
Не совсем понятно, для чего использовать такую реализацию. Насколько мне удалось разобраться, сначала мы отправляем список URL на удаление в `FanIn`, разбиваем его на отдельные URL и отправляем их в общий канал, который читает метод `DeletedURLs(...)` — который, в свою очередь, собирает эти URL обратно в общий список и отправляет на удаление, и, ожидая завершения удаления, возвращает управление. Проблема в том, что если мы уберём это и просто отправим список на удаление в `updateDatabase(...)`, ничего не изменится.

Дело в том, что эта реализация к тому же не совсем соответствует постановке задачи: *В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted. Фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно.*

Мне кажется, что простая реализация могла бы выглядеть как-то так:

- При старте приложения мы запускаем горутину (воркер) или несколько воркеров (я рекомендую начать с одного) в методе `main`, которая читает из канала (буфера), когда он наполняется, и для всех задач на выполнение из буфера формирует батч, который выполняет, обновляя URLs. Потом приостанавливает работу, пока буфер опять не наполнится.
- Хендлеры, получив запрос на удаление, отправляют задачи на удаление в канал, из которого читает наша горутина, и сразу (не дожидаясь выполнения) возвращают ответ пользователю.

2024-09-04 03:00 UTC, vokinneberg commented on internal/service/auth/auth.go
> +//func (sa *ServiceAuth) CheckUserDB(userID string) error {
Не стоит оставлять закомментированный код так как он засоряет кодовую базу. Если без этого нельзя обойтись, стоит оставить комментарий с пояснением о том, почему это необходимо.

2024-09-04 03:00 UTC, vokinneberg commented on internal/service/delURLs.go
> +func (s *Service) DeletedURLs(doneCh chan struct{}, urlCh chan string, userID string) error {
Не совсем понятно назначение компонента, который просто проксирует вызовы. Возможно от него можно просто избавиться?

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/db/db.go
> +        user_id UUID,
Так как мы модифицируем базу в существующем приложении база может уже существовать, соотвественно стоит расширять ее либо отдельной командой, либо использовать миграции.

2024-09-04 03:00 UTC, vokinneberg commented on internal/storage/db/delDB.go
> +func (p *PstStorage) DeletedURLs(doneCh chan struct{}, urlCh chan string, userID string) error {
Я бы не советовал реализовывать такую обработку в слое доступа к БД. Лучше для этого как мне кажется подходит сервисный слой.

2024-09-04 05:30 UTC, kamencov commented on internal/service/auth/auth.go
> +//func (sa *ServiceAuth) CheckUserDB(userID string) error {
+

2024-09-04 05:33 UTC, kamencov commented on internal/storage/db/saveDB.go
> +	}
именно так не работает, сработало &userID

2024-09-04 05:35 UTC, kamencov commented on internal/storage/db/checkOriginalURL.go
> +	return nil
+

2024-09-05 00:00 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением четвертого спринта! 🎉 Желаю удачи на выпускном проекте! 🍀

2024-09-05 06:00 UTC, merged