Iter23
kamencov/go-musthave-shortener-tpl pull request #26
Opened 2024-11-14 18:28 UTC by kamencov

2024-11-20 03:07 UTC, vokinneberg requested changes
Поздравляю с первым ревью девятого спринта! 🎉 Продолжаем улучшать наше приложение и покрывать его тестами! ⚡ По традиции хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Ты реализовал функционал, требующийся по ТЗ 👍
2. Ты улучшил покрытие кода тестами 🙌

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Вообще, в идеале при GracefulShutdown как-то подождать, пока `worker` остановится, так как мы ему дали знать, что надо остановиться, и завершили приложение. Можно, например, использовать для этого WaitGroup или ErrorGroup.
2. В `worker` есть логическая проблема: если мы в начале метода сделали `wg.Add(1)`, и при этом сразу получили `!ok`, то мы всегда будем ждать в `wg.Wait()` на строке 50, так как никто не сделает `wg.Done()`. То же самое на строке 59 — никто не сделает ответный `wg.Done()` для вызова на строке 44.

```go
// StartWorkerDeletion стартует воркер для удаления URL из хранилища.
func (w *WorkerDeleted) StartWorkerDeletion(ctx context.Context) {
	var wg *sync.WaitGroup
	for {
		select {
		case req, ok := <-deleteQueue:
			if !ok {
				wg.Wait()
				return
			}
			wg.Add(1)
			go func() {
				defer wg.Done()
				w.processDeletion(ctx, req)
			}()
		case <-ctx.Done():
			wg.Wait()
			return
		}
	}
}
```

Либо передавать `wg` , как параметр:

```go
// StartWorkerDeletion стартует воркер для удаления URL из хранилища.
func (w *WorkerDeleted) StartWorkerDeletion(ctx context.Context, wg *sync.WaitGroup) {
	for {
		select {
		case req, ok := <-deleteQueue:
			if !ok {
				return
			}
			wg.Add(1)
			go func() {
				defer wg.Done()
				w.processDeletion(ctx, req)
			}()
		case <-ctx.Done():

			return
		}
	}
}
```

А в `main` ожидать завершения всех текущих воркеров:

```go
	// Запуск worker'а
	var wg *sync.WaitGroup
	go worker.StartWorkerDeletion(ctx, wg)
	
	....
	cancel()  // Завершаем контекст для worker
	wg.Wait() // Ожидаем завершения всех запросов
	logs.Info("Shutdown complete")
```

2024-11-20 03:07 UTC, vokinneberg commented on cmd/shortener/config.go
> +func (c *Configs) loadConfig() error {
Маленькое предложение по именованию - в нашем случае слово `Config` в названии метода немного избыточно, так как и так понятно, что метод относится к структуре `Configs`. При этом информации о том, что конфиг загружается из файла потеряна, а она является ключевой. Если переименуем метод `loadFromFile` решим обе проблемы. 
```suggestion
func (c *Configs) loadFromFile() error {
```

2024-11-20 03:07 UTC, vokinneberg commented on cmd/shortener/config_test.go
> +	}
Мне кажется проще сделать так и не будет двусмысленности. Вот здесь есть неплохие комментарии от команды Go https://go.dev/wiki/TestComments#table-driven-tests-vs-multiple-test-functions.
```suggestion
	if err != nil {
		t.Errorf("loadConfig() = %v", err)
	}
```

2024-11-20 03:07 UTC, vokinneberg commented on cmd/shortener/config.go
> +	HTTPS      *bool  `json:"enable_https"`
Здесь указатель используется для того чтобы отличить `false` от отсутствующего значения?

2024-11-20 03:07 UTC, vokinneberg commented on cmd/shortener/main.go
> +	cancel() // Завершаем контекст для worker
Вообще в идеале здесь как то подождать пока `worker` остановиться, так как мы ему дали знать, что надо остановиться и завершили приложение. Можно например использовать для этого WaitGroup или ErrorGroup.

2024-11-20 03:07 UTC, vokinneberg commented on internal/storage/db/getDB_test.go
> +			//if !errors.Is(err, tt.expectedErr) {
Не стоит оставлять закомментированный код в репозитории. Это засоряет кодовую базу.

2024-11-20 03:07 UTC, vokinneberg commented on internal/storage/db/getDB_test.go
> +				require.ErrorIs(t, err, tt.expectedErr)
Где-то ты используешь assert библиотеку, а где-то нет. Стоило бы привести эту практику все-таки к общему виду.

2024-11-20 03:07 UTC, vokinneberg commented on internal/workers/worker.go
> +	wg.Add(1)
Возможно стоит эту WaitGroup передать сюда в качестве параметра и ожидать на ней при завершении сервиса.

2024-11-20 03:07 UTC, vokinneberg commented on internal/workers/worker.go
> +				wg.Wait() // Ждем завершения всех горутин удаления
Тут есть логическая проблема, если мы в начале метода сделали `wg.Add(1)` и при этом сразу получили `!ok` то мы всегда будем ждать в `wg.Wait()` на строке 50, так как никто не сделает `wg.Done()`. То же самое на строке 59 - ни кто не сделает ответный `wg.Done()` для вызова на строке 44.

```Go
// StartWorkerDeletion стартует воркер для удаления URL из хранилища.
func (w *WorkerDeleted) StartWorkerDeletion(ctx context.Context) {
	var wg *sync.WaitGroup
	for {
		select {
		case req, ok := <-deleteQueue:
			if !ok {
				wg.Wait()
				return
			}
			wg.Add(1)
			go func() {
				defer wg.Done()
				w.processDeletion(ctx, req)
			}()
		case <-ctx.Done():
			wg.Wait()
			return
		}
	}
}
```

2024-11-20 04:15 UTC, kamencov commented on cmd/shortener/config.go
> +func (c *Configs) loadConfig() error {
спасибо за рекомендацию, применил

2024-11-20 04:15 UTC, kamencov commented on cmd/shortener/config_test.go
> +	}
спасибо за рекомендацию, применил

2024-11-20 04:15 UTC, kamencov commented on cmd/shortener/config.go
> +	HTTPS      *bool  `json:"enable_https"`
да, так как ошибку вызывал, есть какое то другое решение?

2024-11-20 04:16 UTC, kamencov commented on cmd/shortener/main.go
> +	cancel() // Завершаем контекст для worker
использовал второй вариант с прокидование wg в worker

2024-11-20 04:16 UTC, kamencov commented on internal/storage/db/getDB_test.go
> +				require.ErrorIs(t, err, tt.expectedErr)
убрал

2024-11-20 04:16 UTC, kamencov commented on internal/storage/db/getDB_test.go
> +			//if !errors.Is(err, tt.expectedErr) {
убрал

2024-11-20 04:17 UTC, kamencov commented on internal/workers/worker.go
> +	wg.Add(1)
исправил

2024-11-20 04:17 UTC, kamencov commented on internal/workers/worker.go
> +				wg.Wait() // Ждем завершения всех горутин удаления
спасибо за разъяснение, теперь понял логику

2024-11-22 02:17 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью девятого спринта! 🎉 Ты значительно улучшил штатное завершение сервиса. Так держать! 🙌

2024-11-22 14:11 UTC, merged